import { MovieHallStructure } from './types';

export const movieHallStructure: MovieHallStructure = {
  name: 'PVR Cinemas',
  sections: [
    {
      id: 'SEC300',
      name: 'Recliner',
      price: 500,
      rows: [
        {
          id: 'L',
          seats: [
            { id: 'L1', seat: 'L1', isSold: true },
            { id: 'L2', seat: 'L2', isSold: false },
            { id: 'L3', seat: 'L3', isSold: true },
            { id: 'L4', seat: 'L4', isSold: false },
            { id: 'L5', seat: 'L5', isSold: true },
            { id: 'L6', seat: 'L6', isSold: true },
            { id: 'L7', seat: 'L7', isSold: true },
            { id: 'L8', seat: 'L8', isSold: true },
            { id: 'L9', seat: 'L9', isSold: true },
            { id: 'L10', seat: 'L10', isSold: false },
            { id: 'L11', seat: 'L11', isSold: false },
            { id: 'L12', seat: 'L12', isSold: false },
            { id: 'L13', seat: 'L13', isSold: true },
            { id: 'L14', seat: 'L14', isSold: false },
            { id: 'L15', seat: 'L15', isSold: true },
            { id: 'L16', seat: 'L16', isSold: true },
            { id: 'L17', seat: 'L17', isSold: true },
            { id: 'L18', seat: 'L18', isSold: false },
            { id: 'L19', seat: 'L19', isSold: false },
            { id: 'L20', seat: 'L20', isSold: false },
            { id: 'L21', seat: 'L21', isSold: false },
            { id: 'L22', seat: 'L22', isSold: false },
            { id: 'L23', seat: 'L23', isSold: false },
            { id: 'L24', seat: 'L24', isSold: false },
            { id: 'L25', seat: 'L25', isSold: false },
            { id: 'L26', seat: 'L26', isSold: false },
            { id: 'L27', seat: 'L27', isSold: false },
            { id: 'L28', seat: 'L28', isSold: false },
            { id: 'L29', seat: 'L29', isSold: false },
          ],
        },
        {
          id: 'K',
          seats: [
            { id: 'K1', seat: 'K1', isSold: false },
            { id: 'K2', seat: 'K2', isSold: false },
            { id: 'K3', seat: 'K3', isSold: false },
            { id: 'K4', seat: 'K4', isSold: false },
            { id: 'K100X', seat: null, isSold: false },
            { id: 'K101X', seat: null, isSold: false },
            { id: 'K5', seat: 'K5', isSold: false },
            { id: 'K6', seat: 'K6', isSold: false },
            { id: 'K7', seat: 'K7', isSold: false },
            { id: 'K8', seat: 'K8', isSold: false },
            { id: 'K9', seat: 'K9', isSold: false },
            { id: 'K10', seat: 'K10', isSold: false },
            { id: 'K11', seat: 'K11', isSold: false },
            { id: 'K12', seat: 'K12', isSold: false },
            { id: 'K13', seat: 'K13', isSold: false },
            { id: 'K14', seat: 'K14', isSold: false },
            { id: 'K15', seat: 'K15', isSold: true },
            { id: 'K16', seat: 'K16', isSold: true },
            { id: 'K17', seat: 'K17', isSold: true },
            { id: 'K18', seat: 'K18', isSold: true },
            { id: 'K106X', seat: null, isSold: false },
            { id: 'K107X', seat: null, isSold: false },
            { id: 'K19', seat: 'K19', isSold: false },
            { id: 'K20', seat: 'K20', isSold: false },
            { id: 'K21', seat: 'K21', isSold: false },
            { id: 'K22', seat: 'K22', isSold: true },
            { id: 'K23', seat: 'K23', isSold: true },
            { id: 'K24', seat: 'K24', isSold: true },
            { id: 'K25', seat: 'K25', isSold: true },
          ],
        },
        {
          id: 'J',
          seats: [
            { id: 'J101X', seat: null, isSold: false },
            { id: 'J101X', seat: null, isSold: false },
            { id: 'J101X', seat: null, isSold: false },
            { id: 'J101X', seat: null, isSold: false },
            { id: 'J100X', seat: null, isSold: false },
            { id: 'J101X', seat: null, isSold: false },
            { id: 'J5', seat: 'J5', isSold: false },
            { id: 'J6', seat: 'J6', isSold: false },
            { id: 'J7', seat: 'J7', isSold: false },
            { id: 'J8', seat: 'J8', isSold: false },
            { id: 'J9', seat: 'J9', isSold: false },
            { id: 'J10', seat: 'J10', isSold: false },
            { id: 'J11', seat: 'J11', isSold: false },
            { id: 'J12', seat: 'J12', isSold: false },
            { id: 'J13', seat: 'J13', isSold: false },
            { id: 'J14', seat: 'J14', isSold: false },
            { id: 'J15', seat: 'J15', isSold: false },
            { id: 'J16', seat: 'J16', isSold: false },
            { id: 'J17', seat: 'J17', isSold: false },
            { id: 'J18', seat: 'J18', isSold: false },
            { id: 'J106X', seat: null, isSold: false },
            { id: 'J107X', seat: null, isSold: false },
            { id: 'J19', seat: 'J19', isSold: false },
            { id: 'J20', seat: 'J20', isSold: false },
            { id: 'J21', seat: 'J21', isSold: false },
            { id: 'J22', seat: 'J22', isSold: false },
            { id: 'J23', seat: 'J23', isSold: false },
            { id: 'J24', seat: 'J24', isSold: false },
            { id: 'J25', seat: 'J25', isSold: false },
          ],
        },
        {
          id: 'I',
          seats: [
            {
              id: 'I1',
              seat: 'I1',
              isSold: false,
            },
            {
              id: 'I2',
              seat: 'I2',
              isSold: false,
            },
            {
              id: 'I3',
              seat: 'I3',
              isSold: false,
            },
            {
              id: 'I4',
              seat: 'I4',
              isSold: false,
            },
            {
              id: 'I100X',
              seat: null,
              isSold: false,
            },
            {
              id: 'I101X',
              seat: null,
              isSold: false,
            },
            {
              id: 'I5',
              seat: 'I5',
              isSold: false,
            },
            {
              id: 'I6',
              seat: 'I6',
              isSold: false,
            },
            {
              id: 'I7',
              seat: 'I7',
              isSold: true,
            },
            {
              id: 'I8',
              seat: 'I8',
              isSold: true,
            },
            {
              id: 'I9',
              seat: 'I9',
              isSold: true,
            },
            {
              id: 'I10',
              seat: 'I10',
              isSold: true,
            },
            {
              id: 'I11',
              seat: 'I11',
              isSold: false,
            },
            {
              id: 'I12',
              seat: 'I12',
              isSold: false,
            },
            {
              id: 'I13',
              seat: 'I13',
              isSold: true,
            },
            {
              id: 'I14',
              seat: 'I14',
              isSold: true,
            },
            {
              id: 'I15',
              seat: 'I15',
              isSold: false,
            },
            {
              id: 'I16',
              seat: 'I16',
              isSold: false,
            },
            {
              id: 'I17',
              seat: 'I17',
              isSold: false,
            },
            {
              id: 'I18',
              seat: 'I18',
              isSold: false,
            },
            {
              id: 'I106X',
              seat: null,
              isSold: false,
            },
            {
              id: 'I107X',
              seat: null,
              isSold: false,
            },
            {
              id: 'I19',
              seat: 'I19',
              isSold: false,
            },
            {
              id: 'I20',
              seat: 'I20',
              isSold: false,
            },
            {
              id: 'I21',
              seat: 'I21',
              isSold: false,
            },
            {
              id: 'I22',
              seat: 'I22',
              isSold: false,
            },
            {
              id: 'I23',
              seat: 'I23',
              isSold: false,
            },
            {
              id: 'I24',
              seat: 'I24',
              isSold: false,
            },
            {
              id: 'I25',
              seat: 'I25',
              isSold: false,
            },
          ],
        },
        {
          id: 'H',
          seats: [
            {
              id: 'H1',
              seat: 'H1',
              isSold: false,
            },
            {
              id: 'H2',
              seat: 'H2',
              isSold: false,
            },
            {
              id: 'H3',
              seat: 'H3',
              isSold: false,
            },
            {
              id: 'H4',
              seat: 'H4',
              isSold: false,
            },
            {
              id: 'H100X',
              seat: null,
              isSold: false,
            },
            {
              id: 'H101X',
              seat: null,
              isSold: false,
            },
            {
              id: 'H5',
              seat: 'H5',
              isSold: false,
            },
            {
              id: 'H6',
              seat: 'H6',
              isSold: false,
            },
            {
              id: 'H7',
              seat: 'H7',
              isSold: false,
            },
            {
              id: 'H8',
              seat: 'H8',
              isSold: false,
            },
            {
              id: 'H9',
              seat: 'H9',
              isSold: true,
            },
            {
              id: 'H10',
              seat: 'H10',
              isSold: true,
            },
            {
              id: 'H11',
              seat: 'H11',
              isSold: true,
            },
            {
              id: 'H12',
              seat: 'H12',
              isSold: true,
            },
            {
              id: 'H13',
              seat: 'H13',
              isSold: true,
            },
            {
              id: 'H14',
              seat: 'H14',
              isSold: false,
            },
            {
              id: 'H15',
              seat: 'H15',
              isSold: false,
            },
            {
              id: 'H16',
              seat: 'H16',
              isSold: false,
            },
            {
              id: 'H17',
              seat: 'H17',
              isSold: false,
            },
            {
              id: 'H18',
              seat: 'H18',
              isSold: false,
            },
            {
              id: 'H106X',
              seat: null,
              isSold: false,
            },
            {
              id: 'H107X',
              seat: null,
              isSold: false,
            },
            {
              id: 'H19',
              seat: 'H19',
              isSold: false,
            },
            {
              id: 'H20',
              seat: 'H20',
              isSold: false,
            },
            {
              id: 'H21',
              seat: 'H21',
              isSold: false,
            },
            {
              id: 'H22',
              seat: 'H22',
              isSold: false,
            },
            {
              id: 'H23',
              seat: 'H23',
              isSold: false,
            },
            {
              id: 'H24',
              seat: 'H24',
              isSold: false,
            },
            {
              id: 'H25',
              seat: 'H25',
              isSold: false,
            },
          ],
        },
        {
          id: 'G',
          seats: [
            {
              id: 'G1',
              seat: 'G1',
              isSold: false,
            },
            {
              id: 'G2',
              seat: 'G2',
              isSold: false,
            },
            {
              id: 'G3',
              seat: 'G3',
              isSold: false,
            },
            {
              id: 'G4',
              seat: 'G4',
              isSold: false,
            },
            {
              id: 'G100X',
              seat: null,
              isSold: false,
            },
            {
              id: 'G101X',
              seat: null,
              isSold: false,
            },
            {
              id: 'G5',
              seat: 'G5',
              isSold: false,
            },
            {
              id: 'G6',
              seat: 'G6',
              isSold: false,
            },
            {
              id: 'G7',
              seat: 'G7',
              isSold: false,
            },
            {
              id: 'G8',
              seat: 'G8',
              isSold: false,
            },
            {
              id: 'G9',
              seat: 'G9',
              isSold: false,
            },
            {
              id: 'G10',
              seat: 'G10',
              isSold: false,
            },
            {
              id: 'G11',
              seat: 'G11',
              isSold: false,
            },
            {
              id: 'G12',
              seat: 'G12',
              isSold: false,
            },
            {
              id: 'G13',
              seat: 'G13',
              isSold: false,
            },
            {
              id: 'G14',
              seat: 'G14',
              isSold: false,
            },
            {
              id: 'G15',
              seat: 'G15',
              isSold: false,
            },
            {
              id: 'G16',
              seat: 'G16',
              isSold: false,
            },
            {
              id: 'G17',
              seat: 'G17',
              isSold: false,
            },
            {
              id: 'G18',
              seat: 'G18',
              isSold: false,
            },
            {
              id: 'G106X',
              seat: null,
              isSold: false,
            },
            {
              id: 'G107X',
              seat: null,
              isSold: false,
            },
            {
              id: 'G19',
              seat: 'G19',
              isSold: false,
            },
            {
              id: 'G20',
              seat: 'G20',
              isSold: false,
            },
            {
              id: 'G21',
              seat: 'G21',
              isSold: false,
            },
            {
              id: 'G22',
              seat: 'G22',
              isSold: true,
            },
            {
              id: 'G23',
              seat: 'G23',
              isSold: true,
            },
            {
              id: 'G24',
              seat: 'G24',
              isSold: true,
            },
            {
              id: 'G25',
              seat: 'G25',
              isSold: true,
            },
          ],
        },
      ],
    },

    {
      id: 'SEC200',
      name: 'Prime',
      price: 350,
      rows: [
        {
          id: 'C',
          seats: [
            { id: 'C1', seat: 'C1', isSold: false },
            { id: 'C2', seat: 'C2', isSold: false },
            { id: 'C3', seat: 'C3', isSold: false },
            { id: 'C4', seat: 'C4', isSold: false },
            { id: 'C100X', seat: null, isSold: false },
            { id: 'C101X', seat: null, isSold: false },
            { id: 'C5', seat: 'C5', isSold: false },
            { id: 'C6', seat: 'C6', isSold: false },
            { id: 'C7', seat: 'C7', isSold: false },
            { id: 'C8', seat: 'C8', isSold: false },
            { id: 'C9', seat: 'C9', isSold: false },
            { id: 'C10', seat: 'C10', isSold: false },
            { id: 'C11', seat: 'C11', isSold: false },
            { id: 'C12', seat: 'C12', isSold: false },
            { id: 'C13', seat: 'C13', isSold: false },
            { id: 'C14', seat: 'C14', isSold: false },
            { id: 'C15', seat: 'C15', isSold: false },
            { id: 'C16', seat: 'C16', isSold: false },
            { id: 'C17', seat: 'C17', isSold: false },
            { id: 'C18', seat: 'C18', isSold: false },
            { id: 'C106X', seat: null, isSold: false },
            { id: 'C107X', seat: null, isSold: false },
            { id: 'C19', seat: 'C19', isSold: false },
            { id: 'C20', seat: 'C20', isSold: false },
            { id: 'C21', seat: 'C21', isSold: false },
            { id: 'C22', seat: 'C22', isSold: false },
            { id: 'C23', seat: 'C23', isSold: false },
            { id: 'C24', seat: 'C24', isSold: false },
            { id: 'C25', seat: 'C25', isSold: false },
          ],
        },
        {
          id: 'D',
          seats: [
            {
              id: 'D1',
              seat: 'D1',
              isSold: false,
            },
            {
              id: 'D2',
              seat: 'D2',
              isSold: false,
            },
            {
              id: 'D3',
              seat: 'D3',
              isSold: false,
            },
            {
              id: 'D4',
              seat: 'D4',
              isSold: false,
            },
            {
              id: 'D100X',
              seat: null,
              isSold: false,
            },
            {
              id: 'D101X',
              seat: null,
              isSold: false,
            },
            {
              id: 'D5',
              seat: 'D5',
              isSold: false,
            },
            {
              id: 'D6',
              seat: 'D6',
              isSold: false,
            },
            {
              id: 'D7',
              seat: 'D7',
              isSold: false,
            },
            {
              id: 'D8',
              seat: 'D8',
              isSold: false,
            },
            {
              id: 'D9',
              seat: 'D9',
              isSold: false,
            },
            {
              id: 'D10',
              seat: 'D10',
              isSold: false,
            },
            {
              id: 'D11',
              seat: 'D11',
              isSold: false,
            },
            {
              id: 'D12',
              seat: 'D12',
              isSold: false,
            },
            {
              id: 'D13',
              seat: 'D13',
              isSold: false,
            },
            {
              id: 'D14',
              seat: 'D14',
              isSold: false,
            },
            {
              id: 'D15',
              seat: 'D15',
              isSold: false,
            },
            {
              id: 'D16',
              seat: 'D16',
              isSold: false,
            },
            {
              id: 'D17',
              seat: 'D17',
              isSold: false,
            },
            {
              id: 'D18',
              seat: 'D18',
              isSold: false,
            },
            {
              id: 'D106X',
              seat: null,
              isSold: false,
            },
            {
              id: 'D107X',
              seat: null,
              isSold: false,
            },
            {
              id: 'D19',
              seat: 'D19',
              isSold: false,
            },
            {
              id: 'D20',
              seat: 'D20',
              isSold: false,
            },
            {
              id: 'D21',
              seat: 'D21',
              isSold: false,
            },
            {
              id: 'D107X',
              seat: null,
              isSold: false,
            },
            {
              id: 'D108X',
              seat: null,
              isSold: false,
            },
            {
              id: 'D109X',
              seat: null,
              isSold: false,
            },
            {
              id: 'D110X',
              seat: null,
              isSold: false,
            },
          ],
        },
        {
          id: 'E',
          seats: [
            {
              id: 'E1',
              seat: 'E1',
              isSold: false,
            },
            {
              id: 'E2',
              seat: 'E2',
              isSold: false,
            },
            {
              id: 'E3',
              seat: 'E3',
              isSold: false,
            },
            {
              id: 'E4',
              seat: 'E4',
              isSold: false,
            },
            {
              id: 'E100X',
              seat: null,
              isSold: false,
            },
            {
              id: 'E101X',
              seat: null,
              isSold: false,
            },
            {
              id: 'E5',
              seat: 'E5',
              isSold: false,
            },
            {
              id: 'E6',
              seat: 'E6',
              isSold: false,
            },
            {
              id: 'E7',
              seat: 'E7',
              isSold: false,
            },
            {
              id: 'E8',
              seat: 'E8',
              isSold: false,
            },
            {
              id: 'E9',
              seat: 'E9',
              isSold: false,
            },
            {
              id: 'E10',
              seat: 'E10',
              isSold: false,
            },
            {
              id: 'E11',
              seat: 'E11',
              isSold: false,
            },
            {
              id: 'E12',
              seat: 'E12',
              isSold: false,
            },
            {
              id: 'E13',
              seat: 'E13',
              isSold: false,
            },
            {
              id: 'E14',
              seat: 'E14',
              isSold: false,
            },
            {
              id: 'E15',
              seat: 'E15',
              isSold: false,
            },
            {
              id: 'E16',
              seat: 'E16',
              isSold: false,
            },
            {
              id: 'E17',
              seat: 'E17',
              isSold: false,
            },
            {
              id: 'E18',
              seat: 'E18',
              isSold: false,
            },
            {
              id: 'E106X',
              seat: null,
              isSold: false,
            },
            {
              id: 'E107X',
              seat: null,
              isSold: false,
            },
            {
              id: 'E19',
              seat: 'E19',
              isSold: false,
            },
            {
              id: 'E20',
              seat: 'E20',
              isSold: false,
            },
            {
              id: 'E21',
              seat: 'E21',
              isSold: false,
            },
            {
              id: 'E107X',
              seat: null,
              isSold: false,
            },
            {
              id: 'E108X',
              seat: null,
              isSold: false,
            },
            {
              id: 'E109X',
              seat: null,
              isSold: false,
            },
            {
              id: 'E110X',
              seat: null,
              isSold: false,
            },
          ],
        },
        {
          id: 'F',
          seats: [
            {
              id: 'F1',
              seat: 'F1',
              isSold: true,
            },
            {
              id: 'F2',
              seat: 'F2',
              isSold: true,
            },
            {
              id: 'F3',
              seat: 'F3',
              isSold: true,
            },
            {
              id: 'F4',
              seat: 'F4',
              isSold: true,
            },
            {
              id: 'F100X',
              seat: null,
              isSold: true,
            },
            {
              id: 'F101X',
              seat: null,
              isSold: true,
            },
            {
              id: 'F5',
              seat: 'F5',
              isSold: false,
            },
            {
              id: 'F6',
              seat: 'F6',
              isSold: true,
            },
            {
              id: 'F7',
              seat: 'F7',
              isSold: true,
            },
            {
              id: 'F8',
              seat: 'F8',
              isSold: false,
            },
            {
              id: 'F9',
              seat: 'F9',
              isSold: true,
            },
            {
              id: 'F10',
              seat: 'F10',
              isSold: true,
            },
            {
              id: 'F11',
              seat: 'F11',
              isSold: true,
            },
            {
              id: 'F12',
              seat: 'F12',
              isSold: true,
            },
            {
              id: 'F13',
              seat: 'F13',
              isSold: false,
            },
            {
              id: 'F14',
              seat: 'F14',
              isSold: false,
            },
            {
              id: 'F15',
              seat: 'F15',
              isSold: false,
            },
            {
              id: 'F16',
              seat: 'F16',
              isSold: false,
            },
            {
              id: 'F17',
              seat: 'F17',
              isSold: false,
            },
            {
              id: 'F18',
              seat: 'F18',
              isSold: false,
            },
            {
              id: 'F106X',
              seat: null,
              isSold: false,
            },
            {
              id: 'F107X',
              seat: null,
              isSold: false,
            },
            {
              id: 'F19',
              seat: 'F19',
              isSold: false,
            },
            {
              id: 'F20',
              seat: 'F20',
              isSold: false,
            },
            {
              id: 'F21',
              seat: 'F21',
              isSold: false,
            },
            {
              id: 'F107X',
              seat: null,
              isSold: false,
            },
            {
              id: 'F108X',
              seat: null,
              isSold: false,
            },
            {
              id: 'F109X',
              seat: null,
              isSold: false,
            },
            {
              id: 'F110X',
              seat: null,
              isSold: false,
            },
          ],
        },
      ],
    },

    {
      id: 'SEC100',
      name: 'Classic',
      price: 200,
      rows: [
        {
          id: 'A',
          seats: [
            { id: 'A96X', seat: null, isSold: false },
            { id: 'A97X', seat: null, isSold: false },
            { id: 'A98X', seat: null, isSold: false },
            { id: 'A99X', seat: null, isSold: false },
            { id: 'A100X', seat: null, isSold: false },
            { id: 'A101X', seat: null, isSold: false },
            { id: 'A5', seat: 'A5', isSold: false },
            { id: 'A6', seat: 'A6', isSold: false },
            { id: 'A7', seat: 'A7', isSold: false },
            { id: 'A8', seat: 'A8', isSold: false },
            { id: 'A9', seat: 'A9', isSold: false },
            { id: 'A10', seat: 'A10', isSold: false },
            { id: 'A11', seat: 'A11', isSold: false },
            { id: 'A12', seat: 'A12', isSold: false },
            { id: 'A13', seat: 'A13', isSold: false },
            { id: 'A14', seat: 'A14', isSold: false },
            { id: 'A15', seat: 'A15', isSold: false },
            { id: 'A16', seat: 'A16', isSold: false },
            { id: 'A17', seat: 'A17', isSold: false },
            { id: 'A18', seat: 'A18', isSold: false },
            { id: 'A106X', seat: null, isSold: false },
            { id: 'A107X', seat: null, isSold: false },
            { id: 'A19', seat: 'A19', isSold: false },
            { id: 'A20', seat: 'A20', isSold: false },
            { id: 'A21', seat: 'A21', isSold: false },
            { id: 'A107X', seat: null, isSold: false },
            { id: 'A108X', seat: null, isSold: false },
            { id: 'A109X', seat: null, isSold: false },
            { id: 'A110X', seat: null, isSold: false },
          ],
        },
        {
          id: 'B',
          seats: [
            { id: 'B96X', seat: null, isSold: false },
            { id: 'B97X', seat: null, isSold: false },
            { id: 'B98X', seat: null, isSold: false },
            { id: 'B99X', seat: null, isSold: false },
            { id: 'B100X', seat: null, isSold: false },
            { id: 'B101X', seat: null, isSold: false },
            { id: 'B5', seat: 'B5', isSold: false },
            { id: 'B6', seat: 'B6', isSold: false },
            { id: 'B7', seat: 'B7', isSold: false },
            { id: 'B8', seat: 'B8', isSold: false },
            { id: 'B9', seat: 'B9', isSold: false },
            { id: 'B10', seat: 'B10', isSold: false },
            { id: 'B11', seat: 'B11', isSold: false },
            { id: 'B12', seat: 'B12', isSold: false },
            { id: 'B13', seat: 'B13', isSold: false },
            { id: 'B14', seat: 'B14', isSold: false },
            { id: 'B15', seat: 'B15', isSold: false },
            { id: 'B16', seat: 'B16', isSold: false },
            { id: 'B17', seat: 'B17', isSold: false },
            { id: 'B18', seat: 'B18', isSold: false },
            { id: 'B106X', seat: null, isSold: false },
            { id: 'B107X', seat: null, isSold: false },
            { id: 'B19', seat: 'B19', isSold: false },
            { id: 'B20', seat: 'B20', isSold: false },
            { id: 'B21', seat: 'B21', isSold: false },
            { id: 'B107X', seat: null, isSold: false },
            { id: 'B108X', seat: null, isSold: false },
            { id: 'B109X', seat: null, isSold: false },
            { id: 'B110X', seat: null, isSold: false },
          ],
        },
      ],
    },
  ],
};
