import { MovieHallStructure } from './types';

export const movieHallStructure: MovieHallStructure = {
  name: 'PVR Cinemas',
  sections: [
    {
      id: 'SEC300',
      name: 'Recliner',
      rows: [
        {
          id: 'L',
          seats: [
            { id: 'L1', seat: 'L1' },
            { id: 'L2', seat: 'L2' },
            { id: 'L3', seat: 'L3' },
            { id: 'L4', seat: 'L4' },
            { id: 'L5', seat: 'L5' },
            { id: 'L6', seat: 'L6' },
            { id: 'L7', seat: 'L7' },
            { id: 'L8', seat: 'L8' },
            { id: 'L9', seat: 'L9' },
            { id: 'L10', seat: 'L10' },
            { id: 'L11', seat: 'L11' },
            { id: 'L12', seat: 'L12' },
            { id: 'L13', seat: 'L13' },
            { id: 'L14', seat: 'L14' },
            { id: 'L15', seat: 'L15' },
            { id: 'L16', seat: 'L16' },
            { id: 'L17', seat: 'L17' },
            { id: 'L18', seat: 'L18' },
            { id: 'L19', seat: 'L19' },
            { id: 'L20', seat: 'L20' },
            { id: 'L21', seat: 'L21' },
            { id: 'L22', seat: 'L22' },
            { id: 'L23', seat: 'L23' },
            { id: 'L24', seat: 'L24' },
            { id: 'L25', seat: 'L25' },
            { id: 'L26', seat: 'L26' },
            { id: 'L27', seat: 'L27' },
            { id: 'L28', seat: 'L28' },
            { id: 'L29', seat: 'L29' },
          ],
        },
        {
          id: 'K',
          seats: [
            { id: 'K1', seat: 'K1' },
            { id: 'K2', seat: 'K2' },
            { id: 'K3', seat: 'K3' },
            { id: 'K4', seat: 'K4' },
            { id: 'K100X', seat: null },
            { id: 'K101X', seat: null },
            { id: 'K5', seat: 'K5' },
            { id: 'K6', seat: 'K6' },
            { id: 'K7', seat: 'K7' },
            { id: 'K8', seat: 'K8' },
            { id: 'K9', seat: 'K9' },
            { id: 'K10', seat: 'K10' },
            { id: 'K11', seat: 'K11' },
            { id: 'K12', seat: 'K12' },
            { id: 'K13', seat: 'K13' },
            { id: 'K14', seat: 'K14' },
            { id: 'K15', seat: 'K15' },
            { id: 'K16', seat: 'K16' },
            { id: 'K17', seat: 'K17' },
            { id: 'K18', seat: 'K18' },
            { id: 'K106X', seat: null },
            { id: 'K107X', seat: null },
            { id: 'K19', seat: 'K19' },
            { id: 'K20', seat: 'K20' },
            { id: 'K21', seat: 'K21' },
            { id: 'K22', seat: 'K22' },
            { id: 'K23', seat: 'K23' },
            { id: 'K24', seat: 'K24' },
            { id: 'K25', seat: 'K25' },
          ],
        },
        {
          id: 'J',
          seats: [
            { id: 'J101X', seat: null },
            { id: 'J101X', seat: null },
            { id: 'J101X', seat: null },
            { id: 'J101X', seat: null },
            { id: 'J100X', seat: null },
            { id: 'J101X', seat: null },
            { id: 'J5', seat: 'J5' },
            { id: 'J6', seat: 'J6' },
            { id: 'J7', seat: 'J7' },
            { id: 'J8', seat: 'J8' },
            { id: 'J9', seat: 'J9' },
            { id: 'J10', seat: 'J10' },
            { id: 'J11', seat: 'J11' },
            { id: 'J12', seat: 'J12' },
            { id: 'J13', seat: 'J13' },
            { id: 'J14', seat: 'J14' },
            { id: 'J15', seat: 'J15' },
            { id: 'J16', seat: 'J16' },
            { id: 'J17', seat: 'J17' },
            { id: 'J18', seat: 'J18' },
            { id: 'J106X', seat: null },
            { id: 'J107X', seat: null },
            { id: 'J19', seat: 'J19' },
            { id: 'J20', seat: 'J20' },
            { id: 'J21', seat: 'J21' },
            { id: 'J22', seat: 'J22' },
            { id: 'J23', seat: 'J23' },
            { id: 'J24', seat: 'J24' },
            { id: 'J25', seat: 'J25' },
          ],
        },
        {
          id: 'I',
          seats: [
            { id: 'I1', seat: 'I1' },
            { id: 'I2', seat: 'I2' },
            { id: 'I3', seat: 'I3' },
            { id: 'I4', seat: 'I4' },
            { id: 'I100X', seat: null },
            { id: 'I101X', seat: null },
            { id: 'I5', seat: 'I5' },
            { id: 'I6', seat: 'I6' },
            { id: 'I7', seat: 'I7' },
            { id: 'I8', seat: 'I8' },
            { id: 'I9', seat: 'I9' },
            { id: 'I10', seat: 'I10' },
            { id: 'I11', seat: 'I11' },
            { id: 'I12', seat: 'I12' },
            { id: 'I13', seat: 'I13' },
            { id: 'I14', seat: 'I14' },
            { id: 'I15', seat: 'I15' },
            { id: 'I16', seat: 'I16' },
            { id: 'I17', seat: 'I17' },
            { id: 'I18', seat: 'I18' },
            { id: 'I106X', seat: null },
            { id: 'I107X', seat: null },
            { id: 'I19', seat: 'I19' },
            { id: 'I20', seat: 'I20' },
            { id: 'I21', seat: 'I21' },
            { id: 'I22', seat: 'I22' },
            { id: 'I23', seat: 'I23' },
            { id: 'I24', seat: 'I24' },
            { id: 'I25', seat: 'I25' },
          ],
        },
        {
          id: 'H',
          seats: [
            { id: 'H1', seat: 'H1' },
            { id: 'H2', seat: 'H2' },
            { id: 'H3', seat: 'H3' },
            { id: 'H4', seat: 'H4' },
            { id: 'H100X', seat: null },
            { id: 'H101X', seat: null },
            { id: 'H5', seat: 'H5' },
            { id: 'H6', seat: 'H6' },
            { id: 'H7', seat: 'H7' },
            { id: 'H8', seat: 'H8' },
            { id: 'H9', seat: 'H9' },
            { id: 'H10', seat: 'H10' },
            { id: 'H11', seat: 'H11' },
            { id: 'H12', seat: 'H12' },
            { id: 'H13', seat: 'H13' },
            { id: 'H14', seat: 'H14' },
            { id: 'H15', seat: 'H15' },
            { id: 'H16', seat: 'H16' },
            { id: 'H17', seat: 'H17' },
            { id: 'H18', seat: 'H18' },
            { id: 'H106X', seat: null },
            { id: 'H107X', seat: null },
            { id: 'H19', seat: 'H19' },
            { id: 'H20', seat: 'H20' },
            { id: 'H21', seat: 'H21' },
            { id: 'H22', seat: 'H22' },
            { id: 'H23', seat: 'H23' },
            { id: 'H24', seat: 'H24' },
            { id: 'H25', seat: 'H25' },
          ],
        },
        {
          id: 'G',
          seats: [
            { id: 'G1', seat: 'G1' },
            { id: 'G2', seat: 'G2' },
            { id: 'G3', seat: 'G3' },
            { id: 'G4', seat: 'G4' },
            { id: 'G100X', seat: null },
            { id: 'G101X', seat: null },
            { id: 'G5', seat: 'G5' },
            { id: 'G6', seat: 'G6' },
            { id: 'G7', seat: 'G7' },
            { id: 'G8', seat: 'G8' },
            { id: 'G9', seat: 'G9' },
            { id: 'G10', seat: 'G10' },
            { id: 'G11', seat: 'G11' },
            { id: 'G12', seat: 'G12' },
            { id: 'G13', seat: 'G13' },
            { id: 'G14', seat: 'G14' },
            { id: 'G15', seat: 'G15' },
            { id: 'G16', seat: 'G16' },
            { id: 'G17', seat: 'G17' },
            { id: 'G18', seat: 'G18' },
            { id: 'G106X', seat: null },
            { id: 'G107X', seat: null },
            { id: 'G19', seat: 'G19' },
            { id: 'G20', seat: 'G20' },
            { id: 'G21', seat: 'G21' },
            { id: 'G22', seat: 'G22' },
            { id: 'G23', seat: 'G23' },
            { id: 'G24', seat: 'G24' },
            { id: 'G25', seat: 'G25' },
          ],
        },
      ],
    },

    {
      id: 'SEC200',
      name: 'Prime',
      rows: [
        {
          id: 'C',
          seats: [
            { id: 'C1', seat: 'C1' },
            { id: 'C2', seat: 'C2' },
            { id: 'C3', seat: 'C3' },
            { id: 'C4', seat: 'C4' },
            { id: 'C100X', seat: null },
            { id: 'C101X', seat: null },
            { id: 'C5', seat: 'C5' },
            { id: 'C6', seat: 'C6' },
            { id: 'C7', seat: 'C7' },
            { id: 'C8', seat: 'C8' },
            { id: 'C9', seat: 'C9' },
            { id: 'C10', seat: 'C10' },
            { id: 'C11', seat: 'C11' },
            { id: 'C12', seat: 'C12' },
            { id: 'C13', seat: 'C13' },
            { id: 'C14', seat: 'C14' },
            { id: 'C15', seat: 'C15' },
            { id: 'C16', seat: 'C16' },
            { id: 'C17', seat: 'C17' },
            { id: 'C18', seat: 'C18' },
            { id: 'C106X', seat: null },
            { id: 'C107X', seat: null },
            { id: 'C19', seat: 'C19' },
            { id: 'C20', seat: 'C20' },
            { id: 'C21', seat: 'C21' },
            { id: 'C22', seat: 'C22' },
            { id: 'C23', seat: 'C23' },
            { id: 'C24', seat: 'C24' },
            { id: 'C25', seat: 'C25' },
          ],
        },
        {
          id: 'D',
          seats: [
            { id: 'D1', seat: 'D1' },
            { id: 'D2', seat: 'D2' },
            { id: 'D3', seat: 'D3' },
            { id: 'D4', seat: 'D4' },
            { id: 'D100X', seat: null },
            { id: 'D101X', seat: null },
            { id: 'D5', seat: 'D5' },
            { id: 'D6', seat: 'D6' },
            { id: 'D7', seat: 'D7' },
            { id: 'D8', seat: 'D8' },
            { id: 'D9', seat: 'D9' },
            { id: 'D10', seat: 'D10' },
            { id: 'D11', seat: 'D11' },
            { id: 'D12', seat: 'D12' },
            { id: 'D13', seat: 'D13' },
            { id: 'D14', seat: 'D14' },
            { id: 'D15', seat: 'D15' },
            { id: 'D16', seat: 'D16' },
            { id: 'D17', seat: 'D17' },
            { id: 'D18', seat: 'D18' },
            { id: 'D106X', seat: null },
            { id: 'D107X', seat: null },
            { id: 'D19', seat: 'D19' },
            { id: 'D20', seat: 'D20' },
            { id: 'D21', seat: 'D21' },
            { id: 'D107X', seat: null },
            { id: 'D108X', seat: null },
            { id: 'D109X', seat: null },
            { id: 'D110X', seat: null },
          ],
        },
        {
          id: 'E',
          seats: [
            { id: 'E1', seat: 'E1' },
            { id: 'E2', seat: 'E2' },
            { id: 'E3', seat: 'E3' },
            { id: 'E4', seat: 'E4' },
            { id: 'E100X', seat: null },
            { id: 'E101X', seat: null },
            { id: 'E5', seat: 'E5' },
            { id: 'E6', seat: 'E6' },
            { id: 'E7', seat: 'E7' },
            { id: 'E8', seat: 'E8' },
            { id: 'E9', seat: 'E9' },
            { id: 'E10', seat: 'E10' },
            { id: 'E11', seat: 'E11' },
            { id: 'E12', seat: 'E12' },
            { id: 'E13', seat: 'E13' },
            { id: 'E14', seat: 'E14' },
            { id: 'E15', seat: 'E15' },
            { id: 'E16', seat: 'E16' },
            { id: 'E17', seat: 'E17' },
            { id: 'E18', seat: 'E18' },
            { id: 'E106X', seat: null },
            { id: 'E107X', seat: null },
            { id: 'E19', seat: 'E19' },
            { id: 'E20', seat: 'E20' },
            { id: 'E21', seat: 'E21' },
            { id: 'E107X', seat: null },
            { id: 'E108X', seat: null },
            { id: 'E109X', seat: null },
            { id: 'E110X', seat: null },
          ],
        },
        {
          id: 'F',
          seats: [
            { id: 'F1', seat: 'F1' },
            { id: 'F2', seat: 'F2' },
            { id: 'F3', seat: 'F3' },
            { id: 'F4', seat: 'F4' },
            { id: 'F100X', seat: null },
            { id: 'F101X', seat: null },
            { id: 'F5', seat: 'F5' },
            { id: 'F6', seat: 'F6' },
            { id: 'F7', seat: 'F7' },
            { id: 'F8', seat: 'F8' },
            { id: 'F9', seat: 'F9' },
            { id: 'F10', seat: 'F10' },
            { id: 'F11', seat: 'F11' },
            { id: 'F12', seat: 'F12' },
            { id: 'F13', seat: 'F13' },
            { id: 'F14', seat: 'F14' },
            { id: 'F15', seat: 'F15' },
            { id: 'F16', seat: 'F16' },
            { id: 'F17', seat: 'F17' },
            { id: 'F18', seat: 'F18' },
            { id: 'F106X', seat: null },
            { id: 'F107X', seat: null },
            { id: 'F19', seat: 'F19' },
            { id: 'F20', seat: 'F20' },
            { id: 'F21', seat: 'F21' },
            { id: 'F107X', seat: null },
            { id: 'F108X', seat: null },
            { id: 'F109X', seat: null },
            { id: 'F110X', seat: null },
          ],
        },
      ],
    },

    {
      id: 'SEC100',
      name: 'Classic',
      rows: [
        {
          id: 'A',
          seats: [
            { id: 'A96X', seat: null },
            { id: 'A97X', seat: null },
            { id: 'A98X', seat: null },
            { id: 'A99X', seat: null },
            { id: 'A100X', seat: null },
            { id: 'A101X', seat: null },
            { id: 'A5', seat: 'A5' },
            { id: 'A6', seat: 'A6' },
            { id: 'A7', seat: 'A7' },
            { id: 'A8', seat: 'A8' },
            { id: 'A9', seat: 'A9' },
            { id: 'A10', seat: 'A10' },
            { id: 'A11', seat: 'A11' },
            { id: 'A12', seat: 'A12' },
            { id: 'A13', seat: 'A13' },
            { id: 'A14', seat: 'A14' },
            { id: 'A15', seat: 'A15' },
            { id: 'A16', seat: 'A16' },
            { id: 'A17', seat: 'A17' },
            { id: 'A18', seat: 'A18' },
            { id: 'A106X', seat: null },
            { id: 'A107X', seat: null },
            { id: 'A19', seat: 'A19' },
            { id: 'A20', seat: 'A20' },
            { id: 'A21', seat: 'A21' },
            { id: 'A107X', seat: null },
            { id: 'A108X', seat: null },
            { id: 'A109X', seat: null },
            { id: 'A110X', seat: null },
          ],
        },
        {
          id: 'B',
          seats: [
            { id: 'B96X', seat: null },
            { id: 'B97X', seat: null },
            { id: 'B98X', seat: null },
            { id: 'B99X', seat: null },
            { id: 'B100X', seat: null },
            { id: 'B101X', seat: null },
            { id: 'B5', seat: 'B5' },
            { id: 'B6', seat: 'B6' },
            { id: 'B7', seat: 'B7' },
            { id: 'B8', seat: 'B8' },
            { id: 'B9', seat: 'B9' },
            { id: 'B10', seat: 'B10' },
            { id: 'B11', seat: 'B11' },
            { id: 'B12', seat: 'B12' },
            { id: 'B13', seat: 'B13' },
            { id: 'B14', seat: 'B14' },
            { id: 'B15', seat: 'B15' },
            { id: 'B16', seat: 'B16' },
            { id: 'B17', seat: 'B17' },
            { id: 'B18', seat: 'B18' },
            { id: 'B106X', seat: null },
            { id: 'B107X', seat: null },
            { id: 'B19', seat: 'B19' },
            { id: 'B20', seat: 'B20' },
            { id: 'B21', seat: 'B21' },
            { id: 'B107X', seat: null },
            { id: 'B108X', seat: null },
            { id: 'B109X', seat: null },
            { id: 'B110X', seat: null },
          ],
        },
      ],
    },
  ],
};
